import { config, fields, collection, singleton } from '@keystatic/core'

// Local mode: the editor runs on your Mac (npm run edit) and writes Markdown
// straight into src/content/, which you then commit like any other change.
export default config({
  storage: { kind: 'local' },
  ui: {
    brand: { name: 'Eight4aWish' },
    navigation: {
      Pages: ['home', 'modulesIndex', 'tutorialsIndex', 'about'],
      Content: ['modules', 'tutorials'],
    },
  },

  // Pages whose words live in the template rather than in a collection.
  singletons: {
    home: singleton({
      label: 'Home page',
      path: 'src/content/home',
      format: { data: 'json' },
      schema: {
        heading: fields.text({ label: 'Heading', defaultValue: 'DIY Eurorack' }),
        intro: fields.text({ label: 'Intro', multiline: true }),
        tagline: fields.text({ label: 'Tagline' }),
        tutorialsBlurb: fields.text({ label: 'Tutorials blurb', multiline: true }),
        latestCount: fields.integer({
          label: 'Modules shown on the home page',
          description: 'The rest are behind "See all modules".',
          defaultValue: 4,
        }),
      },
    }),
    modulesIndex: singleton({
      label: 'Modules index page',
      path: 'src/content/modules-index',
      format: { data: 'json' },
      schema: {
        heading: fields.text({ label: 'Heading', defaultValue: 'Modules' }),
        intro: fields.text({ label: 'Intro', multiline: true }),
      },
    }),
    tutorialsIndex: singleton({
      label: 'Tutorials index page',
      path: 'src/content/tutorials-index',
      format: { data: 'json' },
      schema: {
        heading: fields.text({ label: 'Heading', defaultValue: 'Tutorials' }),
        intro: fields.text({ label: 'Intro', multiline: true }),
        footnote: fields.text({
          label: 'Footnote',
          description: 'The highlighted line under the cards. Leave blank to hide it.',
          multiline: true,
        }),
      },
    }),
    about: singleton({
      label: 'About',
      path: 'src/content/about',
      format: { contentField: 'content' },
      schema: {
        heading: fields.text({ label: 'Heading', defaultValue: 'About' }),
        intro: fields.text({ label: 'Intro', multiline: true }),
        content: fields.markdoc({ label: 'Page content', extension: 'md' }),
      },
    }),
  },
  collections: {
    modules: collection({
      label: 'Modules',
      slugField: 'title',
      path: 'src/content/modules/*',
      format: { contentField: 'content' },
      columns: ['title', 'date'],
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        date: fields.date({
          label: 'Date',
          description: 'Newest modules appear first on the home page.',
          validation: { isRequired: true },
        }),
        summary: fields.text({
          label: 'Summary',
          description: 'One line — this is the text on the card.',
          multiline: true,
          validation: { isRequired: true },
        }),
        platform: fields.text({ label: 'Platform', description: 'Shown as the red chip, e.g. Patch.Init' }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags', itemLabel: (p) => p.value, description: 'Grey chips, e.g. oscillator',
        }),
        panel: fields.text({
          label: 'Panel render (path)',
          description: 'Path under public/, e.g. /renders/daisy_braids_flat.png. Generated by the build scripts — paste the path rather than uploading.',
        }),
        photo: fields.text({
          label: 'Photo of the built module (path)',
          description: 'Path under public/, e.g. /images/daisypibraids.jpeg. The real thing — shown alongside the render.',
        }),
        photoCaption: fields.text({ label: 'Photo caption' }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Built', value: 'built' },
            { label: 'In progress', value: 'in progress' },
            { label: 'Planned', value: 'planned' },
          ],
          defaultValue: 'built',
        }),
        firmware: fields.url({ label: 'Firmware repo' }),
        binary: fields.url({
          label: 'Compiled binary (release asset URL)',
          description: 'The .bin from GitHub Releases — the download for people who will not compile.',
        }),
        extraBinaries: fields.array(
          fields.object({
            label: fields.text({ label: 'Button label', description: 'e.g. Joy Lite' }),
            url: fields.url({ label: 'Release asset URL' }),
            version: fields.text({ label: 'Version' }),
          }),
          { label: 'Extra builds', itemLabel: (p) => p.fields.label.value || 'Build' },
        ),
        firmwareVersion: fields.text({ label: 'Firmware version', description: 'e.g. v1.0.0' }),
        flashWith: fields.select({
          label: 'Flashing method',
          description: 'Depends on how the firmware is built: a Daisy BOOT_NONE build flashes direct; a BOOT_QSPI build needs the bootloader + SD card.',
          options: [
            { label: 'Daisy — direct (BOOT_NONE, fits internal flash)', value: 'daisy-direct' },
            { label: 'Daisy — bootloader + SD card (BOOT_QSPI)', value: 'daisy-qspi' },
            { label: 'Ksoloti / DFU', value: 'ksoloti' },
            { label: 'UF2 drag-and-drop', value: 'uf2' },
          ],
          defaultValue: 'daisy-direct',
        }),
        stl: fields.text({ label: 'Panel STL link' }),
        step: fields.text({ label: 'Panel STEP link' }),
        video: fields.text({ label: 'YouTube video id', description: 'Leave blank for "coming soon".' }),
        draft: fields.checkbox({ label: 'Draft (hide from the site)', defaultValue: false }),
        content: fields.markdoc({ label: 'Page content', extension: 'md' }),
      },
    }),

    tutorials: collection({
      label: 'Tutorials',
      slugField: 'title',
      path: 'src/content/tutorials/*',
      format: { contentField: 'content' },
      columns: ['title', 'eyebrow'],
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        eyebrow: fields.text({ label: 'Eyebrow', description: 'e.g. Music as code' }),
        date: fields.date({ label: 'Date', validation: { isRequired: true } }),
        summary: fields.text({ label: 'Summary', multiline: true, validation: { isRequired: true } }),
        graphic: fields.text({
          label: 'Graphic (path)',
          description: 'Path under public/, e.g. /renders/tut_circuits.png. Generated by tools/ — paste the path rather than uploading.',
        }),
        chips: fields.array(fields.text({ label: 'Chip' }), { label: 'Chips', itemLabel: (p) => p.value }),
        repo: fields.url({ label: 'Repo' }),
        cta: fields.text({ label: 'Button link', description: 'Where the Start/Read button goes.' }),
        order: fields.integer({ label: 'Order', defaultValue: 0 }),
        video: fields.text({
          label: 'YouTube video id',
          description: 'The page leads with this. Blank shows a "coming soon" slot.',
        }),
        draft: fields.checkbox({ label: 'Draft (hide from the site)', defaultValue: false }),
        songs: fields.array(
          fields.object({
            title: fields.text({ label: 'Song title' }),
            blurb: fields.text({ label: 'Intro line (under the heading)', multiline: true }),
            videoTime: fields.text({
              label: 'Video timestamp',
              description: 'e.g. 4m12s — jumps into the video at this song.',
            }),
            download: fields.text({
              label: 'Download path',
              description: 'The full runnable file, e.g. /lessons/simple_song.js (kept in sync from strudel/lessons).',
            }),
            blocks: fields.array(
              fields.object({
                label: fields.text({ label: 'Section label', description: 'e.g. Parts, Movement, Sections' }),
                code: fields.text({ label: 'Rig code (verbatim)', multiline: true }),
                note: fields.text({
                  label: 'Note',
                  description: 'Plain text; `backticks` and **bold** render inline.',
                  multiline: true,
                }),
              }),
              { label: 'Blocks', itemLabel: (p) => p.fields.label.value || 'Block' },
            ),
          }),
          { label: 'Songs', itemLabel: (p) => p.fields.title.value || 'Song' },
        ),
        content: fields.markdoc({ label: 'Page content', extension: 'md' }),
      },
    }),
  },
})
